title= "Timo Sarkar"

[original]
  name = "riggraz"
  homepage = "https://riggraz.dev/"
  repo = "https://github.com/riggraz/no-style-please"
  
[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = true
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'pygments'
    tabWidth           = 2


[params]
  [params.theme_config]
    back_home_text    = "back"
    date_format       = "2006-01-02"
    isListGroupByDate = false
