baseURL = 'https://example.org/'
title = "Timo Sarkar's Website"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.highlight]
  noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true